### ISSUE TITLE
Add "is viewer enabled" check for CModels like PDF

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_downloadable_image#10]
The download block does not show up on the PDF Cmodel - by design, because default PDF Cmodel behaviour is to display a download link already. But we discovered in #9 that using the PDF.js viewer removes the download link, making a Downloadable Datastreams block necessary.

Task: Figure out how to determine if a viewer is enabled for a given CModel, and use that to determine whether or not to show the download block in Islandora Downloadable Datastreams.

@mjordan offered to look into it.

**Comment by mjordan** [comment]
This function is what you want: https://github.com/Islandora/islandora/blob/7.x/includes/solution_packs.inc#L720.

Example:

```php
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  $viewers = islandora_get_viewers(array(), 'islandora:sp_pdf');
```

Returns:

```php
Array
(
    [islandora_pdfjs] => Array
        (
            [label] => pdf.js Reader
            [description] => Mozilla pdf.js Reader.
            [configuration] =>
            [callback] => islandora_pdfjs_viewer_callback
            [model] => Array
                (
                    [0] => islandora:sp_pdf
                    [1] => islandora:bookCModel
                    [2] => islandora:pageCModel
                    [3] => islandora:newspaperIssueCModel
                )

            [mimetype] => Array
                (
                    [0] => application/pdf
                )

        )

)
```

**Comment by bondjimbond** [comment]
Unfortunately, that doesn't work... Here's the output, same as yours I believe:

`Array ( [islandora_pdfjs] => Array ( [label] => pdf.js Reader [description] => Mozilla pdf.js Reader. [configuration] => [callback] => islandora_pdfjs_viewer_callback [model] => Array ( [0] => islandora:sp_pdf [1] => islandora:bookCModel [2] => islandora:pageCModel [3] => islandora:newspaperIssueCModel ) [mimetype] => Array ( [0] => application/pdf ) ) )
`

This is identical whether the viewer is enabled for the content model or not. So it's not helpful for this use case... Basically it detects whether the viewer is **available** for this CModel, not whether it's being used by it.

**Comment by mjordan** [comment]
@bondjimbond just in case, does it still not change if you clear you cache?

**Comment by mjordan** [comment]
Sorry, my bad, the function is https://github.com/Islandora/islandora/blob/7.x/includes/solution_packs.inc#L788. Will supply example in a bit.

**Comment by mjordan** [comment]
Nope - that's not it either, that returns HTML:

```html
Viewer from PDF: <div id="islandora-pdfjs">
  <iframe class="pdf" webkitallowfullscreen mozallowfullscreen allowfullscreen frameborder="no" width="99%" height="800px" src="http://localhost:8000/sites/all/libraries/pdfjs/web/viewer.html?file=/islandora/object/islandora%253A17/datastream/OBJ/view">/islandora/object/islandora%3A17/datastream/OBJ/view</iframe>
</div>
```
Found it: https://github.com/Islandora/islandora/blob/7.x/includes/solution_packs.inc#L811 is it:

```php
module_load_include('inc', 'islandora', 'includes/solution_packs');
  $viewer = islandora_get_viewer_id('islandora_pdf_viewers');
```
returns 'islandora_pdfjs', or if none set, 'none'.

**Comment by bondjimbond** [comment]
OK, so for islandora_get_viewer_id($variable_id), how to get $variable_id? i.e. is there a simple way to go from $object->id->cmodel to $variable_id?

**Comment by mjordan** [comment]
That string is the name of the system variable that each solution pack uses to store its current viewer in. I think you're going to have to look at each solution pack's code.... maybe each pack's .install file is a good place to start.

**Comment by bondjimbond** [comment]
Yeah, I can write that in... what's a good way to write a lookup for that, though? I'd prefer not to have something like:

`if ($ids['cmodel'] == "islandora:sp_pdf" {`
`    $variable_id = "islandora_pdf_viewers"`
`  }`
`  elseif (etc)`
Is there maybe a copypasta array search function I could plug some variables into?

**Comment by mjordan** [comment]
@bondjimbond I recommend establishing a standard mapping of content models to variable names in an associative array, e.g. `$map = array('islandora:sp_pdf' => 'islandora_pdf_viewers', 'someother:cmodel' => 'its_viewers_variable_name')` etc. Just thinking ahead here, but we may also want to define a hook that lets other modules modify the mapping. I'm happy to take that on when the time comes.

**Comment by bondjimbond** [comment]
OK, I think I got that working.

```
   $viewer_map = array(
   'islandora:sp_pdf' => 'islandora_pdf_viewers',
    'ir:thesisCModel' => 'islandora_scholar_viewers',
    'ir:citationCModel' => 'islandora_scholar_viewers',
  );
```

Any other CModels that we need to consider for this function?

**Comment by bondjimbond** [comment]
Sigh.. the point is moot -- I just tested this with Citation and Thesis objects, and on those, the Download link ***doesn't*** disappear when you add the viewer.

Just shows you how much these things weren't designed holistically...
