### ISSUE TITLE
Broaden and expand

### ISSUE THREAD

**Issue by bondjimbond** [bondjimbond/islandora_downloadable_image#2]
Using the selectable CModels from the Badges branch of Islandora Altmetrics, add selectable CModels to the admin form. Then rewrite the module file to only display the block on the selected CModels.

Note that this would probably require setting a configurable (or possibly hard-coded) DSID for every content model that currently exists.

**Comment by bondjimbond** [comment]
@amandarl Saw you forked this module and adapted it to PDFs for the Book SP... would you like to take a look at the moremodels branch and comment on any particulars for broadening the scope?

**Comment by bondjimbond** [comment]
Fixed with #3

**Comment by alehman-loc** [comment]
Oh my this notification got buried I guess, I'm just seeing it now. Apologies!!
