### ISSUE TITLE
Can't seem to get this working for Audio Solution Pack

### ISSUE THREAD

**Issue by axfelix** [bondjimbond/islandora_downloadable_image#8]
Not sure what I'm missing, but this isn't adding any download links to the landing pages of audio objects. Where would you start with debugging?

**Comment by bondjimbond** [comment]
Before anything else - did you enable the download block (in Structure -> Blocks)? And did you check off Audio as one of the allowed cmodels?

**Comment by axfelix** [comment]
Of course, I totally missed that the block had to be enabled. Thanks!

Any way to get the file extension naming to match by default? I think I have a different module for doing in that in a different use case with the binary object SP ...

**Comment by bondjimbond** [comment]
If you want to open a PR with some tweaks, it'd be welcomed!

**Comment by axfelix** [comment]
👍
