### ISSUE TITLE
Block not showing up

### ISSUE THREAD

**Issue by mjordan** [bondjimbond/islandora_downloadable_image#9]
I've enabled this module, placed the block in a region that has other blocks in it ("First sidebar") and made sure my list of content models at `admin/islandora/tools/downloadblock` complete. Yet the block is never showing up, even for the admin user. Anything else I need to do?

**Comment by bondjimbond** [comment]
What kinds of objects is this block displaying at? Do you have a live link to a page where this should be showing?

**Comment by mjordan** [comment]
The content models we're going live with are PDF, video, audio, binary, basic and large image. I can't give you a link here since it's not public yet but I can email you one.

**Comment by bondjimbond** [comment]
As discussed by email, PDF CModel won't work if you're using a viewer:

> Default behaviour for PDF CModel is to have no viewer, and display a download link. If you use the PDF.js viewer, however, it replaces the download link with the viewer.
> 
> I wrote downloadable_datastreams for cmodels that do not have a download link by default, not wanting to add a second link in cases where one already exists… so I probably deliberately excluded the PDF CModel.
> 
> Hmm. Solution? If CModel is PDF, check for presence of viewer… if no viewer, don’t display block. If viewer, display block.
> 
> Any ideas how I’d run such a check?

Basic image has no link because users can just right click to download.

Large image, audio, and video should work. Binary should already have a download link without the module.

Did you test each of these other CModels?

**Comment by mjordan** [comment]
Didn't test the other cmodels yet, but I did change the PDF viewer to none and the Download link appeared. Sorry I missed that feature, thanks for pointing it out. If you want, I can look into seeing if there's a viewer enabled for a given cmodel or object.

**Comment by bondjimbond** [comment]
> Sorry I missed that feature, thanks for pointing it out.

More like I didn't account for the fact that a viewer could remove the download link. :)

> If you want, I can look into seeing if there's a viewer enabled for a given cmodel or object.

Please do! It would be a valuable addition to the module. I enabled PDF.js for PDFs on Arca a while back too, but didn't realize that it killed the download link.
